// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	portal "github.com/TykTechnologies/portal-go"
	mock "github.com/stretchr/testify/mock"
)

// ARsService is an autogenerated mock type for the ARsService type
type ARsService struct {
	mock.Mock
}

// ListARs provides a mock function with given fields: ctx, opts
func (_m *ARsService) ListARs(ctx context.Context, opts ...portal.Option) (*portal.ListARsOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *portal.ListARsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...portal.Option) (*portal.ListARsOutput, error)); ok {
		return rf(ctx, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...portal.Option) *portal.ListARsOutput); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.ListARsOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...portal.Option) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewARsService creates a new instance of ARsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewARsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ARsService {
	mock := &ARsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
