// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	portal "github.com/TykTechnologies/portal-go"
	mock "github.com/stretchr/testify/mock"
)

// Catalogs is an autogenerated mock type for the Catalogs type
type Catalogs struct {
	mock.Mock
}

// CreateCatalog provides a mock function with given fields: ctx, input, opts
func (_m *Catalogs) CreateCatalog(ctx context.Context, input *portal.CatalogInput, opts ...portal.Option) (*portal.CatalogOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *portal.CatalogOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *portal.CatalogInput, ...portal.Option) (*portal.CatalogOutput, error)); ok {
		return rf(ctx, input, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *portal.CatalogInput, ...portal.Option) *portal.CatalogOutput); ok {
		r0 = rf(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.CatalogOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *portal.CatalogInput, ...portal.Option) error); ok {
		r1 = rf(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCatalog provides a mock function with given fields: ctx, id, opts
func (_m *Catalogs) GetCatalog(ctx context.Context, id int64, opts ...portal.Option) (*portal.CatalogOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *portal.CatalogOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...portal.Option) (*portal.CatalogOutput, error)); ok {
		return rf(ctx, id, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...portal.Option) *portal.CatalogOutput); ok {
		r0 = rf(ctx, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.CatalogOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...portal.Option) error); ok {
		r1 = rf(ctx, id, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCatalogs provides a mock function with given fields: ctx, options, opts
func (_m *Catalogs) ListCatalogs(ctx context.Context, options *portal.ListCatalogsInput, opts ...portal.Option) (*portal.ListCatalogsOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, options)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *portal.ListCatalogsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *portal.ListCatalogsInput, ...portal.Option) (*portal.ListCatalogsOutput, error)); ok {
		return rf(ctx, options, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *portal.ListCatalogsInput, ...portal.Option) *portal.ListCatalogsOutput); ok {
		r0 = rf(ctx, options, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.ListCatalogsOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *portal.ListCatalogsInput, ...portal.Option) error); ok {
		r1 = rf(ctx, options, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCatalog provides a mock function with given fields: ctx, id, input, opts
func (_m *Catalogs) UpdateCatalog(ctx context.Context, id int64, input *portal.CatalogInput, opts ...portal.Option) (*portal.CatalogOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *portal.CatalogOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *portal.CatalogInput, ...portal.Option) (*portal.CatalogOutput, error)); ok {
		return rf(ctx, id, input, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *portal.CatalogInput, ...portal.Option) *portal.CatalogOutput); ok {
		r0 = rf(ctx, id, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.CatalogOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *portal.CatalogInput, ...portal.Option) error); ok {
		r1 = rf(ctx, id, input, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCatalogs creates a new instance of Catalogs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCatalogs(t interface {
	mock.TestingT
	Cleanup(func())
}) *Catalogs {
	mock := &Catalogs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
