// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	portal "github.com/edsonmichaque/portal-go"
	mock "github.com/stretchr/testify/mock"
)

// OrgsService is an autogenerated mock type for the OrgsService type
type OrgsService struct {
	mock.Mock
}

// CreateOrg provides a mock function with given fields: ctx, input
func (_m *OrgsService) CreateOrg(ctx context.Context, input portal.OrgInput) (*portal.OrgOutput, error) {
	ret := _m.Called(ctx, input)

	var r0 *portal.OrgOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, portal.OrgInput) (*portal.OrgOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, portal.OrgInput) *portal.OrgOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.OrgOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, portal.OrgInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrg provides a mock function with given fields: ctx, id
func (_m *OrgsService) GetOrg(ctx context.Context, id uint64) (*portal.OrgOutput, error) {
	ret := _m.Called(ctx, id)

	var r0 *portal.OrgOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*portal.OrgOutput, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *portal.OrgOutput); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.OrgOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrgs provides a mock function with given fields: ctx, options
func (_m *OrgsService) ListOrgs(ctx context.Context, options *portal.ListOrgsOptions) (*portal.ListOrgsOutput, error) {
	ret := _m.Called(ctx, options)

	var r0 *portal.ListOrgsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *portal.ListOrgsOptions) (*portal.ListOrgsOutput, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *portal.ListOrgsOptions) *portal.ListOrgsOutput); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.ListOrgsOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *portal.ListOrgsOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrg provides a mock function with given fields: ctx, id, input
func (_m *OrgsService) UpdateOrg(ctx context.Context, id uint64, input portal.OrgInput) (*portal.OrgOutput, error) {
	ret := _m.Called(ctx, id, input)

	var r0 *portal.OrgOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, portal.OrgInput) (*portal.OrgOutput, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, portal.OrgInput) *portal.OrgOutput); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.OrgOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, portal.OrgInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrgsService creates a new instance of OrgsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrgsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrgsService {
	mock := &OrgsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
