// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	portal "github.com/edsonmichaque/portal-go"
	mock "github.com/stretchr/testify/mock"
)

// PlansService is an autogenerated mock type for the PlansService type
type PlansService struct {
	mock.Mock
}

// CreatePlan provides a mock function with given fields: ctx, input
func (_m *PlansService) CreatePlan(ctx context.Context, input portal.PlanInput) (*portal.PlanOutput, error) {
	ret := _m.Called(ctx, input)

	var r0 *portal.PlanOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, portal.PlanInput) (*portal.PlanOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, portal.PlanInput) *portal.PlanOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.PlanOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, portal.PlanInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlan provides a mock function with given fields: ctx, id
func (_m *PlansService) GetPlan(ctx context.Context, id uint64) (*portal.PlanOutput, error) {
	ret := _m.Called(ctx, id)

	var r0 *portal.PlanOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*portal.PlanOutput, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *portal.PlanOutput); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.PlanOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPlans provides a mock function with given fields: ctx, options
func (_m *PlansService) ListPlans(ctx context.Context, options *portal.ListPlansOptions) (*portal.ListPlansOutput, error) {
	ret := _m.Called(ctx, options)

	var r0 *portal.ListPlansOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *portal.ListPlansOptions) (*portal.ListPlansOutput, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *portal.ListPlansOptions) *portal.ListPlansOutput); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.ListPlansOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *portal.ListPlansOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePlan provides a mock function with given fields: ctx, id, input
func (_m *PlansService) UpdatePlan(ctx context.Context, id uint64, input portal.PlanInput) (*portal.PlanOutput, error) {
	ret := _m.Called(ctx, id, input)

	var r0 *portal.PlanOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, portal.PlanInput) (*portal.PlanOutput, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, portal.PlanInput) *portal.PlanOutput); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.PlanOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, portal.PlanInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPlansService creates a new instance of PlansService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlansService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlansService {
	mock := &PlansService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
