// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	portal "github.com/edsonmichaque/portal-go"
	mock "github.com/stretchr/testify/mock"
)

// ProductsService is an autogenerated mock type for the ProductsService type
type ProductsService struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: ctx, input
func (_m *ProductsService) CreateProduct(ctx context.Context, input portal.ProductInput) (*portal.ProductOutput, error) {
	ret := _m.Called(ctx, input)

	var r0 *portal.ProductOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, portal.ProductInput) (*portal.ProductOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, portal.ProductInput) *portal.ProductOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.ProductOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, portal.ProductInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProduct provides a mock function with given fields: ctx, id
func (_m *ProductsService) GetProduct(ctx context.Context, id int64) (*portal.ProductOutput, error) {
	ret := _m.Called(ctx, id)

	var r0 *portal.ProductOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*portal.ProductOutput, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *portal.ProductOutput); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.ProductOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProducts provides a mock function with given fields: ctx, options
func (_m *ProductsService) ListProducts(ctx context.Context, options *portal.ListProductsOptions) (*portal.ListProductsOutput, error) {
	ret := _m.Called(ctx, options)

	var r0 *portal.ListProductsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *portal.ListProductsOptions) (*portal.ListProductsOutput, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *portal.ListProductsOptions) *portal.ListProductsOutput); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.ListProductsOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *portal.ListProductsOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: ctx, id, input
func (_m *ProductsService) UpdateProduct(ctx context.Context, id int64, input portal.ProductInput) (*portal.ProductOutput, error) {
	ret := _m.Called(ctx, id, input)

	var r0 *portal.ProductOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, portal.ProductInput) (*portal.ProductOutput, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, portal.ProductInput) *portal.ProductOutput); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.ProductOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, portal.ProductInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductsService creates a new instance of ProductsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductsService {
	mock := &ProductsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
