// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	portal "github.com/edsonmichaque/portal-go"
	mock "github.com/stretchr/testify/mock"
)

// UsersService is an autogenerated mock type for the UsersService type
type UsersService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, input
func (_m *UsersService) CreateUser(ctx context.Context, input portal.UserInput) (*portal.UserOutput, error) {
	ret := _m.Called(ctx, input)

	var r0 *portal.UserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, portal.UserInput) (*portal.UserOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, portal.UserInput) *portal.UserOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.UserOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, portal.UserInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *UsersService) GetUser(ctx context.Context, id int64) (*portal.UserOutput, error) {
	ret := _m.Called(ctx, id)

	var r0 *portal.UserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*portal.UserOutput, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *portal.UserOutput); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.UserOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsers provides a mock function with given fields: ctx, options
func (_m *UsersService) ListUsers(ctx context.Context, options *portal.ListUsersOptions) (*portal.ListUsersOutput, error) {
	ret := _m.Called(ctx, options)

	var r0 *portal.ListUsersOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *portal.ListUsersOptions) (*portal.ListUsersOutput, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *portal.ListUsersOptions) *portal.ListUsersOutput); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.ListUsersOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *portal.ListUsersOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, id, input
func (_m *UsersService) UpdateUser(ctx context.Context, id int64, input portal.UserInput) (*portal.UserOutput, error) {
	ret := _m.Called(ctx, id, input)

	var r0 *portal.UserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, portal.UserInput) (*portal.UserOutput, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, portal.UserInput) *portal.UserOutput); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*portal.UserOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, portal.UserInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUsersService creates a new instance of UsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersService {
	mock := &UsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
