// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	edp "github.com/edsonmichaque/edp-go"
	mock "github.com/stretchr/testify/mock"
)

// UsersService is an autogenerated mock type for the UsersService type
type UsersService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, input, opts
func (_m *UsersService) CreateUser(ctx context.Context, input *edp.UserInput, opts ...edp.Option) (*edp.UserOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *edp.UserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *edp.UserInput, ...edp.Option) (*edp.UserOutput, error)); ok {
		return rf(ctx, input, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edp.UserInput, ...edp.Option) *edp.UserOutput); ok {
		r0 = rf(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edp.UserOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edp.UserInput, ...edp.Option) error); ok {
		r1 = rf(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: ctx, id, opts
func (_m *UsersService) DeleteUser(ctx context.Context, id int64, opts ...edp.Option) (*edp.UserOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *edp.UserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...edp.Option) (*edp.UserOutput, error)); ok {
		return rf(ctx, id, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...edp.Option) *edp.UserOutput); ok {
		r0 = rf(ctx, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edp.UserOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...edp.Option) error); ok {
		r1 = rf(ctx, id, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, id, opts
func (_m *UsersService) GetUser(ctx context.Context, id int64, opts ...edp.Option) (*edp.UserOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *edp.UserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...edp.Option) (*edp.UserOutput, error)); ok {
		return rf(ctx, id, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, ...edp.Option) *edp.UserOutput); ok {
		r0 = rf(ctx, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edp.UserOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, ...edp.Option) error); ok {
		r1 = rf(ctx, id, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsers provides a mock function with given fields: ctx, options, opts
func (_m *UsersService) ListUsers(ctx context.Context, options *edp.ListUsersInput, opts ...edp.Option) (*edp.ListUsersOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, options)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *edp.ListUsersOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *edp.ListUsersInput, ...edp.Option) (*edp.ListUsersOutput, error)); ok {
		return rf(ctx, options, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edp.ListUsersInput, ...edp.Option) *edp.ListUsersOutput); ok {
		r0 = rf(ctx, options, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edp.ListUsersOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edp.ListUsersInput, ...edp.Option) error); ok {
		r1 = rf(ctx, options, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, id, input, opts
func (_m *UsersService) UpdateUser(ctx context.Context, id int64, input *edp.UserInput, opts ...edp.Option) (*edp.UserOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *edp.UserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *edp.UserInput, ...edp.Option) (*edp.UserOutput, error)); ok {
		return rf(ctx, id, input, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *edp.UserInput, ...edp.Option) *edp.UserOutput); ok {
		r0 = rf(ctx, id, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edp.UserOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *edp.UserInput, ...edp.Option) error); ok {
		r1 = rf(ctx, id, input, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUsersService creates a new instance of UsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersService {
	mock := &UsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
